ixigo:
  postgres:
    host: localhost
    user: ${POSTGRES_USER:REPLACE_ME}
    password: ${POSTGRES_PASSW:REPLACE_ME}
  telegram:
    enabled: false
    token: ${TELEGRAM_BOT_TOKEN:xxxxxx}
    chat-group-id: ${TELEGRAM_CHAT_GROUP_ID:xxxxxx}
  demmanager:
    demfileprops:
      root-folder: "C:\\Temp\\demfiles"
      parser-environment: "WINDOWS"             # Enum: WINDOWS, RASP
      parser-execution-type: "SYNC"             # Enum: ASYNC, SYNC
      parser-exec-path: "E:\\Workspaces\\Git\\csgo_util\\DemParser\\bin\\Debug\\netcoreapp3.1\\DemParser.dll"       # This is the full path to the DemParser executable
      