ixigo:
  postgres:
    host: localhost
    user: ${POSTGRES_USER:REPLACE_ME}
    password: ${POSTGRES_PASSW:REPLACE_ME}
  telegram:
    enabled: false
    token: ${TELEGRAM_BOT_TOKEN:xxxxxx}
    chat-group-id: ${TELEGRAM_CHAT_GROUP_ID:xxxxxx}
  demmanager:
    demfileprops:
      root-folder: "C:\\Temp\\demfiles"
      parser-environment: "WINDOWS"             # Enum: WINDOWS, RASP
      parser-execution-type: "SYNC"             # Enum: ASYNC, SYNC
      parser-exec-path: "E:\\Workspaces\\Git\\csgo_util\\DemParser\\bin\\Debug\\netcoreapp3.1\\DemParser.dll"       # This is the full path to the DemParser executable
  end-points:    
    gateway:
      protocol: "https://"
      domain: "localhost"
      port: 8763
      base-url: "${ixigo.end-points.gateway.protocol}${ixigo.end-points.gateway.domain}:${ixigo.end-points.gateway.port}/ixigoproxy"
    demmanager:
      gateway-path: "ixigo-dem-manager"
      base-url: "${ixigo.end-points.gateway.base-url}/${ixigo.end-points.demmanager.gateway-path}/demmanager"
      post-dem-file: "${ixigo.end-points.demmanager.base-url}/files"
      get-dem-file: "${ixigo.end-points.demmanager.base-url}/files/%s"
      remove-dem-file-from-queue: "${ixigo.end-points.demmanager.base-url}/files/%s"
      post-parse-queued-files: "${ixigo.end-points.demmanager.base-url}/parse/queued"
      post-parse-all-files: "${ixigo.end-points.demmanager.base-url}/parse/all"
      