ixigo:
  postgres:
    host: localhost
    user: ${POSTGRES_USER:REPLACE_ME}
    password: ${POSTGRES_PASSW:REPLACE_ME}
  telegram:
    enabled: false
    token: ${TELEGRAM_BOT_TOKEN:xxxxxx}
    chat-group-id: ${TELEGRAM_CHAT_GROUP_ID:xxxxxx}
      