server:
  port: 8081
com:
  marco:
    ixigo:
      demmanager:
        demFileManager:
          rootFolder: '/demFiles'
        notifications:
          telegram:
            enabled: false
        demparser:
          environment: RASP # Enum: WINDOWS, RASP
          executionType: ASYNC # Enum: ASYNC, SYNC
          dotnetexecutable: '/demParser/DemParser'
            
spring:
  datasource:
    url: jdbc:postgresql://dbpostgres:5432/demfiles